### ISSUE TITLE
如果服务关了，数据库有变化，重启时收不到变化的事件

### ISSUE THREAD

**Issue by lengmianshi** [giafei/mysql-binlog-watcher#2]
难道服务就不能停吗？

**Comment by lengmianshi** [comment]
我自己保存同步的时间戳，重启时以这个时间戳为起点来同步一次，搞定

**Comment by giafei** [comment]
这个是Mysql binlog 的特性， 做主从的时候也会碰到这个问题。从底层是没办法解决的。
但你能找到解决方案，赞
